base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerPage, name="register"),

    path('', views.home, name="home"),
    path('job/<str:pk>/', views.job, name="job"),
    path('profile/<str:pk>/', views.userProfile, name="user-profile"),
    path('balance/<str:pk>/', views.userBalance, name="user-balance"),

    path('create-job/', views.createJob, name="create-job"),
    path('update-job/<str:pk>/', views.updateJob, name="update-job"),
    path('delete-job/<str:pk>/', views.deleteJob, name="delete-job"),
    path('delete-message/<str:pk>/', views.deleteMessage, name="delete-message"),

    path('update-user/', views.updateUser, name="update-user"),

    path('topics/', views.topicsPage, name="topics"),
    path('activity/', views.activityPage, name="activity"),

    path('update-jira/', views.updateJira, name="update-jira"),
]

goodfreelance/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(unique=True)
    bio = models.TextField(null=True)

    avatar = models.ImageField(null=True, default='avatar.svg')

    balance = models.DecimalField(max_digits=20, decimal_places=2, null=False, default=0)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    
class Transaction(models.Model):
    name = models.CharField(max_length=200, null=True)
    amount = models.DecimalField(max_digits=20, decimal_places=2, null=False, default=0)
    addition = models.BooleanField(null=False, default=True)
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    
class JobStatus(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    
class Job(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    cost = models.DecimalField(max_digits=20, decimal_places=2, null=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    status = models.ForeignKey(JobStatus, on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['-updated', '-created']

class MatchType(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    
class Match(models.Model):
    job = models.ForeignKey(Job, on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    created = models.DateTimeField(auto_now_add=True)
    
    type = models.ForeignKey(MatchType, on_delete=models.SET_NULL, null=True)
    
    class Meta:
        ordering = ['-created']

class ReviewType(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Review(models.Model):
    rating = models.SmallIntegerField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    type = models.ForeignKey(ReviewType, on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['-created']

class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    body = models.TextField() 
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.body[0:50]

base/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .models import Job, User
from django import forms


class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['name', 'username', 'email', 'password1', 'password2']
    pass


class JobForm(ModelForm):
    class Meta:
        model = Job
        fields = ['name', 'description', 'topic', 'cost']
        exclude = []
        widgets = {
            'cost' : forms.TextInput(attrs = {'placeholder': '1000 золотых'}),
        }
        


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['avatar', 'name', 'username', 'email', 'bio']
        widgets = {
            'avatar': forms.TextInput(attrs={'placeholder': 'аватар', "title": "аватар"}),
            'name': forms.TextInput(attrs={'placeholder': 'имя', "title": "имя"}),
            'username': forms.TextInput(attrs={'placeholder': 'логин', "title": "логин"}),
            'bio': forms.TextInput(attrs={'placeholder': 'био', "title": "био"}),
        }

base/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout
from .models import User, Topic, JobStatus, Job, MatchType, Match, ReviewType, Review, Message
from .forms import JobForm, UserForm, MyUserCreationForm
import re

def get_user_context(user):
    if not user.is_authenticated:
        return {}
    transactions = user.transaction_set.all()
    balance = sum([x.amount if x.addition == 1 else -x.amount for x in transactions])
    context = {
        'balance': int(balance)
    }
    return context

def loginPage(request):
    page = 'login'
    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':
        email = request.POST.get('email').lower()
        password = request.POST.get('password')

        try:
            user = User.objects.get(email=email)
        except:
            messages.error(request, 'Пользователь не существует')

        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'Неправильный логин или пароль')

    context = {'page': page}
    return render(request, 'base/login_register.html', context)


def logoutUser(request):
    logout(request)
    return redirect('home')


def registerPage(request):
    form = MyUserCreationForm()

    if request.method == 'POST':
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'An error occurred during registration')

    return render(request, 'base/login_register.html', {'form': form})


def get_customer(job):
    customer_id = Match.objects.filter(job=job, type=MatchType.objects.get_or_create(name='Customer')[0]).values('user')[0]
    return User.objects.get(id=customer_id['user'])

def get_job_to_customer(jobs):
    job_to_customer = {}  # Создаем пустой словарь

    for job in jobs:
        customer = get_customer(job)
        if customer:
            job_to_customer[job] = customer
    
    return job_to_customer

def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''

    jobs = Job.objects.filter(
        Q(topic__name__icontains=q) |
        Q(name__icontains=q) |
        Q(description__icontains=q)
    )

    topics = Topic.objects.all()[0:5]
    job_count = jobs.count()
    job_messages = Message.objects.filter(
        Q(job__topic__name__icontains=q))[0:3]

    job_to_customer = get_job_to_customer(jobs)  

    context = {'jobs': jobs, 
               'job_to_customer': job_to_customer, 
               'topics': topics,
               'job_count': job_count, 
               'job_messages': job_messages}
    
    context.update(get_user_context(request.user))
    return render(request, 'base/home.html', context)


def job(request, pk):
    job = Job.objects.get(id=pk)
    job_messages = job.message_set.all()
    participants_id = Match.objects.filter(job=job).values('user')
    participants = User.objects.filter(id__in=[user_id['user'] for user_id in participants_id])
    print()
    if request.method == 'POST':
        message = Message.objects.create(
            user=request.user,
            job=job,
            body=request.POST.get('body')
        )
        message.save()
        if Match.objects.filter(user=request.user).count() == 0:
            match = Match.objects.create(
                job = job,
                user = request.user,
                type = MatchType.objects.get_or_create(name='Participant')[0]
            )
            match.save()
        return redirect('job', pk=job.id)
    
    customer_id = Match.objects.filter(job=job, type=MatchType.objects.get_or_create(name='Customer')[0]).values('user')
    job_customer = User.objects.filter(id=customer_id[0]['user'])[0]
    context = {'job': job, 'job_messages': job_messages,
               'participants': participants,
               'job_customer': job_customer}
    context.update(get_user_context(request.user))
    return render(request, 'base/job.html', context)


def userProfile(request, pk):
    user = User.objects.get(id=pk)
    jobs = Job.objects.filter(id__in=[x['job'] for x in 
        Match.objects.filter(user=user, type=MatchType.objects.get_or_create(name='Customer')[0].id).values('job')
    ])
    job_messages = user.message_set.all()
    topics = Topic.objects.all()
    job_to_customer = get_job_to_customer(jobs)
    context = {'user': user, 'job_to_customer': job_to_customer,
               'job_messages': job_messages, 'topics': topics}
    context.update(get_user_context(request.user))
    return render(request, 'base/profile.html', context)

@login_required(login_url='login')
def userBalance(request, pk):
    user = User.objects.get(id=pk)
    transactions = user.transaction_set.all()
    context = {
        'user': user,
        'transactions': transactions,
    }
    context.update(get_user_context(request.user))
    return render(request, f'base/balance.html', context)


def get_cost(str_cost):
    arr = re.findall(r'\d+', str_cost)
    if len(arr) > 1 and int(arr[1]) < 100:
        return float(arr[0]) + float(arr[1]) * 0.01
    elif len(arr) > 0:
        return arr[0]
    return 0


@login_required(login_url='login')
def createJob(request):
    form = JobForm()
    topics = Topic.objects.all()
    if request.method == 'POST':
        topic_name = request.POST.get('topic')
        topic, created = Topic.objects.get_or_create(name=topic_name)

        job = Job.objects.create(
            topic=topic,
            name=request.POST.get('name'),
            description=request.POST.get('description'),
            status = JobStatus.objects.get_or_create(name='Find performer')[0],
            cost=get_cost(request.POST.get('cost')),
        )
        
        job.save()
        match = Match.objects.create(
            job = job,
            user = request.user,
            type = MatchType.objects.get_or_create(name='Customer')[0],
        )
        match.save()
        return redirect('home')

    context = {'form': form, 'topics': topics}
    context.update(get_user_context(request.user))
    return render(request, 'base/job_form.html', context)


@login_required(login_url='login')
def updateJob(request, pk):
    job = Job.objects.get(id=pk)
    form = JobForm(instance=job)
    topics = Topic.objects.all()
    customer_id = Match.objects.filter(job=job, type=MatchType.objects.get_or_create(name='Customer')[0]).values('user')
    job_customer = User.objects.filter(id=customer_id[0]['user'])[0]
    if request.user != job_customer:
        return HttpResponse('Your are not allowed here!!')

    if request.method == 'POST':
        topic_name = request.POST.get('topic')
        topic, created = Topic.objects.get_or_create(name=topic_name)
        job.name = request.POST.get('name')
        job.topic = topic
        job.description = request.POST.get('description')
        job.cost = get_cost(request.POST.get('cost'))
        job.save()
        return redirect('home')

    context = {'form': form, 'topics': topics, 'job': job}
    context.update(get_user_context(request.user))
    return render(request, 'base/job_form.html', context)

def get_customer(job):
    customer_id = Match.objects.filter(job=job, type=MatchType.objects.get_or_create(name='Customer')[0]).values('user')
    job_customer = User.objects.filter(id=customer_id[0]['user'])[0]
    return job_customer

@login_required(login_url='login')
def deleteJob(request, pk):
    job = Job.objects.get(id=pk)
    job_customer = get_customer(job)

    if request.user != job_customer:
        return HttpResponse('Your are not allowed here!!')

    if request.method == 'POST':
        job.delete()
        return redirect('home')
    context = {'obj': job}
    context.update(get_user_context(request.user))
    return render(request, 'base/delete.html', context)


@login_required(login_url='login')
def deleteMessage(request, pk):
    message = Message.objects.get(id=pk)

    if request.user != message.user:
        return HttpResponse('Your are not allowed here!!')

    if request.method == 'POST':
        message.delete()
        return redirect('home')
    
    context = {'obj': message}
    context.update(get_user_context(request.user))
    return render(request, 'base/delete.html', context)


@login_required(login_url='login')
def updateUser(request):
    user = request.user
    form = UserForm(instance=user)

    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('user-profile', pk=user.id)
    context = {'form': form}
    context.update(get_user_context(request.user))
    return render(request, 'base/update-user.html', context)


def topicsPage(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    topics = Topic.objects.filter(name__icontains=q)
    context = {'topics': topics}
    context.update(get_user_context(request.user))
    return render(request, 'base/topics.html', context)


def activityPage(request):
    job_messages = Message.objects.all()
    context = {'job_messages': job_messages}
    context.update(get_user_context(request.user))
    return render(request, 'base/activity.html', context)

# jira super loader

import os
import requests
import sys
# https://docs.google.com/spreadsheets/d/1KfqpJ0u4K9htCjQTiZC4V6tzLwZQCCoa9XLBIQCMk7c/edit?usp=sharing
def getGoogleSeet(spreadsheet_id, outDir, outFile):
  

base/templates/base/activity.html
{% extends 'main.html' %}

{% block content %}
<main class="layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'home' %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>назад</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
              </path>
            </svg>
          </a>
          <h3>Недавние послания</h3>
        </div>
      </div>

      <div class="activities-page layout__body">

        {% for message in job_messages %}
        <div class="activities__box">
          <div class="activities__boxHeader jobListJob__header">
            <a href="{% url 'user-profile' message.user.id %}" class="jobListJob__author">
              <div class="avatar avatar--small">
                <img src="{{message.user.avatar.url}}" />
              </div>
              <p>
                @{{message.user}}
                <span>{{message.created|timesince}} назад</span>
              </p>
            </a>

            {% if request.user == message.user %}
            <div class="jobListJob__actions">
              <a href="{% url 'delete-message' message.id %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>remove</title>
                  <path
                    d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
                  </path>
                </svg>
              </a>
            </div>
            {% endif %}

          </div>
          <div class="activities__boxContent">
            <p>replied to post “<a href="{% url 'job' message.job.id %}">{{message.job}}</a>”</p>
            <div class="activities__boxJobContent">
              {{message.body}}
            </div>
          </div>
        </div>
        {% endfor %}

      </div>
    </div>
  </div>
</main>
{% endblock content %}

base/templates/base/activity_component.html
<div class="activities">
    <!-- <a href="{% url 'activity' %}"> -->
        <div class="activities__header">
            <h2>Недавние послания</h2>
        </div>
    <!-- </a> -->
    {% for message in job_messages %}
    <div class="activities__box">
        <div class="activities__boxHeader jobListJob__header">
            <a href="{% url 'user-profile' message.user.id %}" class="jobListJob__author">
                <div class="avatar avatar--small">
                    <img src="{{message.user.avatar.url}}" />
                </div>
                <p>
                    @{{message.user.username}}
                    <span>{{message.created|timesince}} назад</span>
                </p>
            </a>

            {% if request.user == message.user %}
            <div class="jobListJob__actions">
                <a href="{% url 'delete-message' message.id %}">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                        <title>remove</title>
                        <path
                            d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
                        </path>
                    </svg>
                </a>
            </div>
            {% endif %}

        </div>
        <div class="activities__boxContent">
            <div>Ответ на квест <a href="{% url 'job' message.job.id %}">“{{message.job.name}}”</a></div>
            <div class="activities__boxJobContent">{{message.body}}</div>
        </div>
    </div>
    {% endfor %}

</div>

base/templates/base/balance.html
{% extends 'main.html' %}

{% block content %}
<main class="user__balance">
    <div class="container">
      <div class="balance__box">
        <div class="balance__boxHeader">
          <div class="balance__boxTitle">
            <a href="{{request.META.HTTP_REFERER}}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>назад</title>
                <path
                  d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                </path>
              </svg>
            </a>
            <h3>Мешок золота</h3>
          </div>
          <!--<button class="recharge-button">Пополнить мешок</button>-->
        </div>
        <div class="balance__body">
          <form class="balance__view" action="" method="POST">
            {% csrf_token %}
            <label for="job_topic">У вас в мешке: {{balance}} золотых</label>
          </form>
          <table class="transaction-table">
            <thead>
              <tr>
                <th>Дата</th>
                <th>Действие</th>
                <th>Сумма</th>
                <th>Источник</th>
              </tr>
            </thead>
            <tbody>
              {% for transaction in transactions %}
              <tr>
                <td>{{transaction.created}}</td>
                {% if transaction.addition == 1 %}
                <td>Пополнение</td>
                {% else %}
                <td>Расход</td>
                {% endif %}
                <td>{{transaction.amount}} золотых</td>
                <td>{{transaction.name}}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </main>
  
{% endblock content %}

base/templates/base/delete.html
{% extends 'main.html' %}

{% block content %}
<main class="delete-item layout">
    <div class="container">
        <div class="layout__box">
            <div class="layout__boxHeader">
                <div class="layout__boxTitle">
                    <a href="{{request.META.HTTP_REFERER}}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                            viewBox="0 0 32 32">
                            <title>назад</title>
                            <path
                                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                            </path>
                        </svg>
                    </a>
                    <h3>Назад</h3>
                </div>
            </div>
            <div class="layout__body">
                <form class="form" method="POST" action="">
                    {% csrf_token %}
                    <div class="form__group">
                        <p>Вы уверены что хотите удалить сообщение "{{obj}}"?</p>
                    </div>

                    <div class="for__group">
                        <input class="btn btn--main" type="submit" value="Подтвердить" />
                    </div>

                </form>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

base/templates/base/feed_component.html
{% for job, job_customer  in job_to_customer.items %}
<div class="jobListJob">
    <div class="jobListJob__header">

        <a href="{% url 'user-profile' job_customer.id %}" class="jobListJob__author">
            <div class="avatar avatar--small">
                <img src="{{job_customer.avatar.url}}" />
            </div>
            <span>@{{job_customer.username}}</span>
        </a>
        <div class="jobListJob__actions">
            <span>{{job.created|timesince}} назад</span>
        </div>
    </div>
    <div class="jobListJob__content">
        <a href="{% url 'job' job.id %}">{{job.name}}</a>
        <p><span class="cost">{{job.cost}} золотых</span></p>
    </div>
    <div class="jobListJob__meta">
        <a href="{% url 'job' job.id %}" class="jobListJob__joined">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>user-group</title>
                <path
                    d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z">
                </path>
                <path
                    d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z">
                </path>
                <path
                    d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z">
                </path>
                <path
                    d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z">
                </path>
            </svg>
            {{job_participants.count}} Присоединилось
        </a>
        <p class="jobListJob__topic">{{job.topic.name}}</p>
    </div>
</div>
{% endfor %}

base/templates/base/profile.html
{% extends 'main.html' %}

{% block content %}
<main class="profile-page layout layout--3">
  <div class="container">
    <!-- Topics Start -->
    {% include 'base/topics_component.html' %}
    <!-- Topics End -->

    <!-- Job List Start -->
    <div class="jobList">
      <div class="profile">
        <div class="profile__avatar">
          <div class="avatar avatar--large active">
            <img src="{{user.avatar.url}}" />
          </div>
        </div>
        <div class="profile__info">
          <h3>{{user.name}}</h3>
          <p>@{{user.username}}</p>
          {% if request.user == user %}
          <a href="{% url 'update-user' %}" class="btn btn--main btn--pill">Edit Profile</a>
          {% endif %}
        </div>
        <div class="profile__about">
          <h3>Описание</h3>
          <p>
            {{user.bio}}
          </p>
        </div>
      </div>

      <div class="jobList__header">
        <div>
          <h2>Квесты размещённые {{user.name}}</a>
          </h2>
        </div>
      </div>
      {% include 'base/feed_component.html' %}


    </div>
    <!-- Job List End -->

    <!-- Activities Start -->
    {% include 'base/activity_component.html' %}
    <!-- Activities End -->
  </div>
</main>
{% endblock content %}

base/templates/base/topics.html
{% extends 'main.html' %}

{% block content %}
<main class="create-job layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'home' %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>назад</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
            </svg>
          </a>
            <h3>Поиск по квестам</h3>
        </div>
      </div>

      <div class="topics-page layout__body">
        <form action="" method="GET" class="header__search">
          <label>
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z">
              </path>
            </svg>
            <input name="q" placeholder="Поиск по квестам" />
          </label>
        </form>

        <ul class="topics__list">
          <li>
            <a href="{% url 'topics' %}" class="active">All <span>{{topics.count}}</span></a>
          </li>
          {% for topic in topics %}
          <li>
            <a href="{% url 'home' %}?q={{topic.name}}">{{ topic.name }} <span>{{topic.job_set.all.count}}</span></a>
          </li>
          {% endfor %}

        </ul>
      </div>
    </div>
  </div>
</main>

{% endblock content %}

base/templates/base/topics_component.html
<div class="topics">
    <a href="{% url 'topics' %}">
        <div class="topics__header">
                <h2>Поиск по квестам</h2> 
        </div>
    </a>
    <ul class="topics__list">
        <li>
            <a href="{% url 'home' %}" class="active">All <span>{{jobs.count}}</span></a>
        </li>
        {% for topic in topics %}
        <li>
            <a href="{% url 'home' %}?q={{topic.name}}">{{topic.name}}<span>{{topic.job_set.all.count}}</span></a>
        </li>
        {% endfor %}

    </ul>
    <a class="btn btn--link" href="{% url 'topics' %}">
        Раскрыть
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>chevron-down</title>
            <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
        </svg>
    </a>
</div>